deps: bump com.google.truth:truth from 1.4.1 to 1.4.2 (#1354)
Bumps [com.google.truth:truth](https://togithub.com/google/truth) from 1.4.1 to 1.4.2.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://togithub.com/google/truth/releases">com.google.truth:truth's releases</a>.</em></p>
<blockquote>
<h2>1.4.2</h2>
<p>This release is the final step of copying all our methods from <code>Truth8</code> to <code>Truth</code>. If you have not already migrated your usages from <code>Truth8</code> to <code>Truth</code>, you may see build errors:</p>
<pre><code>OptionalSubjectTest.java:39: error: reference to assertThat is ambiguous
    assertThat(Optional.of(&quot;foo&quot;)).isPresent();
    ^
  both method assertThat(@org.checkerframework.checker.nullness.qual.Nullable Optional&lt;?&gt;) in Truth8 and method assertThat(@org.checkerframework.checker.nullness.qual.Nullable Optional&lt;?&gt;) in Truth match
</code></pre>
<p>In most cases, you can migrate your whole project mechanically: <code>git grep -l Truth8 | xargs perl -pi -e 's/\bTruth8\b/Truth/g;'</code>. (You can make that change before upgrading to Truth 1.4.2 or as part of the same commit.)</p>
<p>If you instead need to migrate your project incrementally (for example, because it is very large), you may want to upgrade your version of Truth incrementally, too, following our instructions for <a href="https://togithub.com/google/truth/releases/tag/v1.3.0">1.3.0</a> and <a href="https://togithub.com/google/truth/releases/tag/v1.4.0">1.4.0</a>.</p>
<h2>For help</h2>
<p>Please feel welcome to <a href="https://togithub.com/google/truth/issues/new">open an issue</a> to report problems or request help.</p>
<h2>Changelog</h2>
<ul>
<li>Removed temporary type parameters from <code>Truth.assertThat(Stream)</code> and <code>Truth.assertThat(Optional)</code>. This can create build errors, which you can fix by replacing all your references to <code>Truth8</code> with references to <code>Truth</code>. (45782bd0e)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://togithub.com/google/truth/commit/0ca7ef06fda6b740406fc1402447a8a9ff61ee35"><code>0ca7ef0</code></a> Set version number for truth-parent to 1.4.2.</li>
<li><a href="https://togithub.com/google/truth/commit/e3b435498a88f389c4aeafa711230465d2c76c17"><code>e3b4354</code></a> Enable a few more Guava Primitives tests for J2KT</li>
<li><a href="https://togithub.com/google/truth/commit/ae78f4a04c84a11569d31a81107301140237151b"><code>ae78f4a</code></a> Bump actions/setup-java from 4.0.0 to 4.1.0</li>
<li><a href="https://togithub.com/google/truth/commit/996a844c3ef62055ae5dcb73edf6eadb3e0ab881"><code>996a844</code></a> Remove more copies of a workaround for an ancient Android bug.</li>
<li><a href="https://togithub.com/google/truth/commit/a43223ef586ecbf0a34dabe9f0dc3a965672051f"><code>a43223e</code></a> Suppress <code>TruthSelfEquals</code> violations in Truth.</li>
<li><a href="https://togithub.com/google/truth/commit/559d6360e3c82265328a64f1a328f5b2d8c3e652"><code>559d636</code></a> Suppress <code>NullableOptional</code>, as we already do in, e.g., `Truth.assertThat(Opt...</li>
<li><a href="https://togithub.com/google/truth/commit/3efe35324062046383036aab71472a94cb454ca1"><code>3efe353</code></a> Automated Code Change</li>
<li><a href="https://togithub.com/google/truth/commit/5efd53f1064b4b6f0d8b156034b0c21c0b6a5713"><code>5efd53f</code></a> Change <code>assertThat(array)</code> to allow arrays of non-nullable elements</li>
<li><a href="https://togithub.com/google/truth/commit/bbd8d1218bccf79fada58885c30fd6356650a5e6"><code>bbd8d12</code></a> Bump com.google.errorprone:error_prone_annotations from 2.24.1 to 2.25.0</li>
<li><a href="https://togithub.com/google/truth/commit/c2439618ee956cca31424472d5fb023e99892ae9"><code>c243961</code></a> Remove <code>@J2ktIncompatible</code> from <code>StringSubject#matches</code></li>
<li>Additional commits viewable in <a href="https://togithub.com/google/truth/compare/v1.4.1...v1.4.2">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=com.google.truth:truth&package-manager=maven&previous-version=1.4.1&new-version=1.4.2)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>